[project]
name = "Irreversible Variational Solvers"
authors = [
    {name = "Andrés A León Baldelli", email = "leon.baldelli@cnrs.fr"},
    ]
version = "0.0.1"
requires-python = ">=3.8"

# Short description
description = "Three solvers for irreversible evolutionary processes with
  a general energetic notion of stability."

# Path to README.md
readme = "README.md"

# Path to license file
license = {file = "LICENSE"}

# Direct dependencies
dependencies = [
    "pandas>=2.2",
    "sympy",
    "numpy>=1.26.0",
    "matplotlib",
    "mpi4py>=3.1.5"
    "slepc4py==3.20.1",
    "petsc4py>=3.20.5",
    "gmsh>=4.12.2",
    "PyYAML>=6.0.1",
    "scipy>=1.12.0",
    "pyvista>=0.43",
]