name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - '*'

jobs:
  build-image-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Run Docker container
        run: docker run --rm -v "$(pwd)":/home/numerix -w /home/numerix kumiori3/numerix:stable

      - name: Install Irrevolutions
        run: pip install .